### ISSUE TITLE
Learning Clojure progress

### ISSUE THREAD

**Issue by meadch** [meadch/meadch#1]
<details>
<summary>Getting Clojure</summary>

### Part I
  - [x] Chapter 1: Hello, Clojure
  - [x] Chapter 2: Vectors and Lists
  - [x] Chapter 3: Maps, Keywords, and Sets
  - [x] Chapter 4: Logic
  - [x] Chapter 5: More Capable Functions
  - [x] Chapter 6: Functional Things
  - [x] Chapter 7: Let
  - [x] Chapter 8: Def, Symbols and Vars
  - [x] Chapter 9: Namespaces

### Part II
  - [x] Chapter 10: Sequences
  - [x] Chapter 11: Lazy Sequences
  - [x] Chapter 12: Destructuring
  - [x] Chapter 13: Records and Protocols
  - [x] Chapter 14: Tests
  - [x] Chapter 15: Spec

### Part III
  - [x] Chapter 16: Interoperating with Java
  - [x] Chapter 17: Threads, Promises and Futures
  - [ ] Chapter 18: State

</details>
<details>

<summary>Exercism (Clojure track)</summary>

  - [x] Hello World
  - [x] Two Fer

</details>

<details>
<summary>Clojure from the Ground Up</summary>

- [ ] [macros](https://aphyr.com/posts/305-clojure-from-the-ground-up-macros)
- [ ] [state](https://aphyr.com/posts/306-clojure-from-the-ground-up-state)
- [ ] [logistics](https://aphyr.com/posts/311-clojure-from-the-ground-up-logistics)

</details>

<details>
<summary>4Clojure</summary>

- [x] 20 problems
- [ ] 40 problems
- [ ] 60 problems
- [ ] 80 problems
- [ ] 100 problems

</details>

<details>
<summary>ClojureScript, Reagent, re-frame</summary>

- [ ] build an app with plain hiccup and JS interop
- [ ] build an app with reagent
- [ ] build an app with re-frame

</details>

<details>
<summary>DataScript</summary>

- [ ] complete http://learndatalogtoday.org/
- [ ] build an app with datascript

</details>
<details>

<summary>Learn in Public</summary>

- [x] day 1

_Getting Clojure_

:ballot_box_with_check:  Chapter 1: Hello, Clojure

Lovely quote: "The irony of picking up a new programming language is that while the goal is to write perfect code, a key skill is to learn how to deal with the myriad of mistakes you’re going to make along the way."

:bookmark:  Chapter 2: Vectors and Lists (stopped at In the Wild)

I didn't know about the relationship between immutability and persistence:

> The computer-science term for immutable data structures that support the manufacture of very fast almost-the-same copies is persistent, as in persistent data structures. This is a very different use of the word persistent than most professional programmers are used to. Keep in mind that in Clojure, a persistent data structure is immutable and efficient and is not necessarily destined to be stored in a database or a file or anywhere else.

- [x] [day 2](https://discord.com/channels/708122962422792194/738734449155637290/751055427088678912)
- [x] [day 3](https://discord.com/channels/708122962422792194/738734449155637290/751416498114920579)
- [x] [day 4](https://discord.com/channels/708122962422792194/738734449155637290/751761870657945601)
- [x] [day 5](https://discord.com/channels/708122962422792194/738734449155637290/752167679930138716)
- [x] [day 6](https://discord.com/channels/708122962422792194/738734449155637290/752514688104792085)
- [x] [day 7](https://discord.com/channels/708122962422792194/738734449155637290/752863048166932660)
- [x] [day 8](https://discord.com/channels/708122962422792194/738734449155637290/753229389302333450)
- [x] [day 9](https://discord.com/channels/708122962422792194/738734449155637290/753607069554311298)
- [x] [day 10](https://discord.com/channels/708122962422792194/738734449155637290/753949791104401419)
- [ ] day 11
- [ ] day 12
- [ ] day 13
- [ ] day 14
- [ ] day 15
- [ ] day 16
- [ ] day 17
- [ ] day 18
- [ ] day 19
- [ ] day 20
- [ ] day 21
- [ ] day 22
- [ ] day 23
- [ ] day 24
- [ ] day 25
- [ ] day 26
- [ ] day 27
- [ ] day 28
- [ ] day 29
- [ ] day 30
- [ ] day 31
- [ ] day 32
- [ ] day 33
- [ ] day 34
- [ ] day 35

</details>
